[versions]
android-sdk-tools = "33.0.1"
android-sdk-min = "24"
android-sdk-compile = "33"
android-cmake = "3.22.1"
android-ndk = "25.2.9519653"

kotlin = "1.8.10"
agp = "7.4.1"
wire = "4.4.3"

[libraries]
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-compiler = { module = "com.squareup.wire:wire-compiler", version.ref = "wire" }
