name: Kotlin Multiplatform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Kotlin Dependencies
      run: tools/install-kotlin-dependencies

    - name: Build KMP Sample
      run: |
        ./gradlew --version
        ./gradlew assemble
      working-directory: samples/kmp
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
